env_file: "creds.env" #optional, specify your environment variable file for API keys and other secrets

tracing:
  type: "default"
  params:
    enabled: false
    tracking_uri: null # set your tracking URI (if available)
    experiment_name: "trustifai_experiment"

llm:
  type: "mistral" #openai, huggingface, gemini, mistral, ollama, azure_ai, nvidia_nim etc. (LiteLLM models)
  params:
    model_name: "mistral-small-2506" # specify your model name here
    api_type: "chat_completion" # "chat_completion" (default) or "responses"
  kwargs:
    temperature: 0.01
    max_tokens: 4096
    top_p: 0.95
    max_retries: 5
    timeout: 300
    logprobs: true
    # chat_template_kwargs: {"enable_thinking": False}

embeddings:
  type: "openrouter" #openai, huggingface, gemini, mistral, ollama, azure etc. (LiteLLM embed models)
  params:
    model_name: "openai/text-embedding-3-small"
  kwargs: {}

metrics:
  - type: "evidence_coverage"
    enabled: true
    params:
      strategy: "llm" #reranker, llm
      STRONG_GROUNDING: 0.85
      PARTIAL_GROUNDING: 0.6
      
  - type: "consistency"
    enabled: true
    params:
      STABLE_CONSISTENCY: 0.85
      FRAGILE_CONSISTENCY: 0.6

  - type: "source_diversity"
    enabled: true
    params:
      HIGH_DIVERSITY: 0.85
      MODERATE_DIVERSITY: 0.6

  - type: "semantic_drift"
    enabled: true
    params:
      STRONG_ALIGNMENT: 0.85
      PARTIAL_ALIGNMENT: 0.6

  - type: "trust_score"
    params:
      RELIABLE_TRUST: 0.8
      ACCEPTABLE_TRUST: 0.6

score_weights:
  - type: "evidence_coverage"
    params:
      weight: 0.40
  - type: "consistency"
    params:
      weight: 0.20
  - type: "source_diversity"
    params:
      weight: 0.10
  - type: "semantic_drift"
    params:
      weight: 0.30
